apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
  - name: cleanup
    image: alpine
    script: |
      rm -rf /workspace/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  steps:
  - name: run-tests
    image: python:3.8
    script: |
      pip install nose flake8
      flake8 .
      nosetests
